
#ifndef MATRIX_MULTIPLICATOR_OPENCL_KERNEL_READER_H
#define MATRIX_MULTIPLICATOR_OPENCL_KERNEL_READER_H

#include "main.h"

string readMatrixMultiplierKernel();

#endif //MATRIX_MULTIPLICATOR_OPENCL_KERNEL_READER_H
