
#ifndef MATRIX_MULTIPLICATOR_OPENCL_KERNEL_READER_H
#define MATRIX_MULTIPLICATOR_OPENCL_KERNEL_READER_H

#include "sobel.h"

string readBruteForceKernel();

#endif //MATRIX_MULTIPLICATOR_OPENCL_KERNEL_READER_H
